camunda:
  bpm:
    webapp:
      index-redirect-enabled: true
    admin-user:
      id: demo
      password: demo
    database:
      jdbc-batch-processing: false
    process-engine-name: rest-engine

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: CAMUNDA
    password: CAMUNDA
    driver-class-name: oracle.jdbc.OracleDriver
    initializationMode: never
server:
  port: 18080